name: Greet Everyone
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Say hello
        run: ./hello.sh
      - name: Echo the greeting's time
        run: echo 'END.'

